version: "3"
services:
    app:
        image: node:10
        user: node
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./app:/home/node/app
        ports:
            - 3000:3000
        command: npm start
    codecept:
        image: codeception/codeceptjs
        depends_on:
            - app
        volumes:
            - ./tests:/tests
